apiVersion: v1
kind: Service
metadata:
  name: gophercon-service
spec:
  type: LoadBalancer
  ports:
  - name: gophercon
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: gophercon
