apiVersion: v1
kind: Service
metadata:
  name: gophercon-service-80
spec:
  type: LoadBalancer
  ports:
  - name: gophercon-80
    port: 80
    targetPort: 8081
    protocol: TCP
  selector:
    app: gophercon
